# Generated by Django 2.1.4 on 2018-12-05 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saleboxecomdjango', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='saleboxecomdjango.MemberGroup'),
        ),
    ]
