# Generated by Django 2.1.4 on 2018-12-06 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saleboxecomdjango', '0002_auto_20181206_0416'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductRatingCache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_count', models.IntegerField()),
                ('score', models.FloatField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saleboxecomdjango.Product')),
            ],
        ),
    ]
