# Generated by Django 2.1.4 on 2018-12-05 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saleboxecomdjango', '0002_auto_20181205_0710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributeitem',
            name='attribute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='saleboxecomdjango.Attribute'),
        ),
    ]
