# Generated by Django 2.1.4 on 2018-12-06 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saleboxecomdjango', '0003_productratingcache'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productratingcache',
            name='score',
            field=models.IntegerField(),
        ),
    ]
