# Generated by Django 2.1.4 on 2018-12-06 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saleboxecomdjango', '0004_auto_20181206_0624'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productratingcache',
            options={'verbose_name': 'Product Rating Cache', 'verbose_name_plural': 'Product Rating Cache'},
        ),
    ]
