# Generated by Django 2.1.4 on 2018-12-06 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saleboxecomdjango', '0005_auto_20181206_0626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='image',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
