# Generated by Django 2.1.4 on 2019-01-29 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saleboxdjango', '0002_auto_20190120_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='attribute_10',
            field=models.ManyToManyField(blank=True, related_name='product_attr_10', to='saleboxdjango.AttributeItem'),
        ),
        migrations.AddField(
            model_name='product',
            name='attribute_5',
            field=models.ManyToManyField(blank=True, related_name='product_attr_5', to='saleboxdjango.AttributeItem'),
        ),
        migrations.AddField(
            model_name='product',
            name='attribute_6',
            field=models.ManyToManyField(blank=True, related_name='product_attr_6', to='saleboxdjango.AttributeItem'),
        ),
        migrations.AddField(
            model_name='product',
            name='attribute_7',
            field=models.ManyToManyField(blank=True, related_name='product_attr_7', to='saleboxdjango.AttributeItem'),
        ),
        migrations.AddField(
            model_name='product',
            name='attribute_8',
            field=models.ManyToManyField(blank=True, related_name='product_attr_8', to='saleboxdjango.AttributeItem'),
        ),
        migrations.AddField(
            model_name='product',
            name='attribute_9',
            field=models.ManyToManyField(blank=True, related_name='product_attr_9', to='saleboxdjango.AttributeItem'),
        ),
        migrations.AddField(
            model_name='product',
            name='string_1',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='string_2',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='string_3',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='string_4',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='attribute_10',
            field=models.ManyToManyField(blank=True, related_name='variant_attr_10', to='saleboxdjango.AttributeItem'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='attribute_7',
            field=models.ManyToManyField(blank=True, related_name='variant_attr_7', to='saleboxdjango.AttributeItem'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='attribute_8',
            field=models.ManyToManyField(blank=True, related_name='variant_attr_8', to='saleboxdjango.AttributeItem'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='attribute_9',
            field=models.ManyToManyField(blank=True, related_name='variant_attr_9', to='saleboxdjango.AttributeItem'),
        ),
    ]
