# Generated by Django 2.1.4 on 2018-12-26 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saleboxdjango', '0002_auto_20181216_0817'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributeitem',
            name='delete_dt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='attribute_3',
            field=models.ManyToManyField(related_name='product_attr_3', to='saleboxdjango.AttributeItem'),
        ),
        migrations.AddField(
            model_name='product',
            name='attribute_4',
            field=models.ManyToManyField(related_name='product_attr_4', to='saleboxdjango.AttributeItem'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='attribute_3',
            field=models.ManyToManyField(related_name='variant_attr_3', to='saleboxdjango.AttributeItem'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='attribute_4',
            field=models.ManyToManyField(related_name='variant_attr_4', to='saleboxdjango.AttributeItem'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='attribute_5',
            field=models.ManyToManyField(related_name='variant_attr_5', to='saleboxdjango.AttributeItem'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='attribute_6',
            field=models.ManyToManyField(related_name='variant_attr_6', to='saleboxdjango.AttributeItem'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='ecommerce_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
