# Generated by Django 2.1.4 on 2018-12-28 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saleboxdjango', '0002_auto_20181227_0807'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='slug_path',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
