# Generated by Django 2.1.4 on 2018-12-07 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saleboxdjango', '0002_basketwishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='basketwishlist',
            name='session',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
