# Generated by Django 2.1.4 on 2018-12-12 03:41

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saleboxdjango', '0002_emailvalidator_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailvalidator',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
