# Generated by Django 2.1.4 on 2018-12-26 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saleboxdjango', '0003_auto_20181226_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributeitem',
            name='slug',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='slug',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='slug',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
