# Generated by Django 2.1.4 on 2018-12-14 03:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('saleboxdjango', '0003_auto_20181212_0341'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default', models.BooleanField(default=False)),
                ('full_name', models.CharField(blank=True, max_length=150, null=True)),
                ('address_1', models.CharField(blank=True, max_length=150, null=True)),
                ('address_2', models.CharField(blank=True, max_length=150, null=True)),
                ('address_3', models.CharField(blank=True, max_length=150, null=True)),
                ('address_4', models.CharField(blank=True, max_length=150, null=True)),
                ('address_5', models.CharField(blank=True, max_length=150, null=True)),
                ('postcode', models.CharField(blank=True, max_length=12, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='saleboxdjango.Country')),
                ('country_state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='saleboxdjango.CountryState')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Address',
                'ordering': ['full_name', 'address_1'],
            },
        ),
    ]
