# Generated by Django 2.1.4 on 2019-01-31 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saleboxdjango', '0003_auto_20190129_1912'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariantRatingCache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_count', models.IntegerField(default=1)),
                ('rating', models.IntegerField(default=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Product Variant Rating Cache',
                'verbose_name': 'Product Variant Rating Cache',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='bestseller_rank',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='rating_cache',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='rating_vote_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='bestseller_rank',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='rating_cache',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='rating_vote_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productvariantratingcache',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saleboxdjango.ProductVariant'),
        ),
    ]
