# Generated by Django 2.1.4 on 2018-12-14 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saleboxdjango', '0004_useraddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='address_1',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='full_name',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
