# Generated by Django 2.1.4 on 2018-12-26 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saleboxdjango', '0004_auto_20181226_0735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='attribute_1',
            field=models.ManyToManyField(blank=True, related_name='product_attr_1', to='saleboxdjango.AttributeItem'),
        ),
        migrations.AlterField(
            model_name='product',
            name='attribute_2',
            field=models.ManyToManyField(blank=True, related_name='product_attr_2', to='saleboxdjango.AttributeItem'),
        ),
        migrations.AlterField(
            model_name='product',
            name='attribute_3',
            field=models.ManyToManyField(blank=True, related_name='product_attr_3', to='saleboxdjango.AttributeItem'),
        ),
        migrations.AlterField(
            model_name='product',
            name='attribute_4',
            field=models.ManyToManyField(blank=True, related_name='product_attr_4', to='saleboxdjango.AttributeItem'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='attribute_1',
            field=models.ManyToManyField(blank=True, related_name='variant_attr_1', to='saleboxdjango.AttributeItem'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='attribute_2',
            field=models.ManyToManyField(blank=True, related_name='variant_attr_2', to='saleboxdjango.AttributeItem'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='attribute_3',
            field=models.ManyToManyField(blank=True, related_name='variant_attr_3', to='saleboxdjango.AttributeItem'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='attribute_4',
            field=models.ManyToManyField(blank=True, related_name='variant_attr_4', to='saleboxdjango.AttributeItem'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='attribute_5',
            field=models.ManyToManyField(blank=True, related_name='variant_attr_5', to='saleboxdjango.AttributeItem'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='attribute_6',
            field=models.ManyToManyField(blank=True, related_name='variant_attr_6', to='saleboxdjango.AttributeItem'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='unique_string',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
