# Generated by Django 2.1.4 on 2019-01-31 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saleboxdjango', '0004_auto_20190131_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productratingcache',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productvariantratingcache',
            name='variant',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='rating_cache',
            new_name='rating_score',
        ),
        migrations.RenameField(
            model_name='productvariant',
            old_name='rating_cache',
            new_name='rating_score',
        ),
        migrations.DeleteModel(
            name='ProductRatingCache',
        ),
        migrations.DeleteModel(
            name='ProductVariantRatingCache',
        ),
    ]
