# Generated by Django 2.1.4 on 2019-02-25 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saleboxdjango', '0005_auto_20190225_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='default_image',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
