# Generated by Django 2.1.4 on 2018-12-15 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saleboxdjango', '0005_auto_20181214_0350'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='address_type',
            field=models.CharField(default='d', max_length=1),
        ),
    ]
