# Generated by Django 2.1.4 on 2019-02-25 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saleboxdjango', '0006_productvariant_default_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='local_image',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='local_image',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='default_image',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='productvariantimage',
            name='local_img',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
