# Generated by Django 2.1.4 on 2018-12-11 06:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('saleboxdjango', '0008_auto_20181211_0217'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailValidator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('e', 'Change Email'), ('f', 'Forgot Password'), ('r', 'Register')], max_length=1)),
                ('hash_string', models.CharField(default='', max_length=64)),
                ('used_flag', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
