# Generated by Django 2.1.4 on 2018-12-11 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saleboxdjango', '0009_emailvalidator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailvalidator',
            name='used_flag',
        ),
    ]
