# Generated by Django 2.1.4 on 2019-03-26 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saleboxdjango', '0009_auto_20190326_1203'),
        ('saleboxdjango', '0007_auto_20190326_0724'),
    ]

    operations = [
    ]
