# Generated by Django 2.1.4 on 2019-03-26 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saleboxdjango', '0010_merge_20190326_1250'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='productvariant',
            name='saleboxdjan_bestsel_f7b707_idx',
        ),
        migrations.RemoveIndex(
            model_name='productvariant',
            name='saleboxdjan_bestsel_54c126_idx',
        ),
        migrations.RemoveIndex(
            model_name='productvariant',
            name='saleboxdjan_sale_pr_21a4e1_idx',
        ),
        migrations.RemoveIndex(
            model_name='productvariant',
            name='saleboxdjan_sale_pr_feafc6_idx',
        ),
        migrations.RemoveIndex(
            model_name='productvariant',
            name='saleboxdjan_rating__8cb616_idx',
        ),
        migrations.RemoveIndex(
            model_name='productvariant',
            name='saleboxdjan_rating__b209b4_idx',
        ),
    ]
